arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - motor_1_to_plastic_1
    - motor_2_to_plastic_2
  constraints:
    motor_1_to_plastic_1:
      goal: 0.1
    motor_2_to_plastic_2:
      goal: 0.1
